### PR TITLE
Better escaping

### LINKED ISSUE #1: String "\" is replaced by ""
```
>>> import expandvars
>>> expandvars.expandvars('D:\\test')
'D:test'
```

### PR DESCRIPTION
**Pull request by Toilal**
Close #1

### CODE REVIEW

**Comment by Toilal** [comment]
I tried to improve the build, but it fails with older python 3 version on TravisCI.

**Comment by sayanarijit** [comment]
It would be best if you could just fix the target issue in this PR and create a separate issue and PR with the other proposed changes. It's cleaner this way and easy to revert in case we need to.

**Comment by Toilal** [comment]
I've removed changes from setup.py, but it still fails on python 3.3 for some reason I'm not sure I want to investigate more :)

**Comment by sayanarijit** [comment]
Dropped 3.3 in https://github.com/sayanarijit/expandvars/issues/4
Do the following :
```bash
git remote add prod https://github.com/sayanarijit/expandvars
git pull --rebase prod master
git push origin Toilal:setuptools
```
I'll be able to merge it then.

**Comment by Toilal** [comment]
Done, build is OK now

**Comment by Toilal** [comment]
Thanks, do you plan a pipy release ?

**Comment by sayanarijit** [comment]
On it.

**Comment by sayanarijit** [comment]
[Released](https://pypi.org/project/expandvars/0.3/) 🙂

**Pull request merged**
