### PR TITLE
Follow setuptools standard to run tests and add tox configuration

### PR DESCRIPTION
**Pull request by Toilal**
Work in progress to fix build issues

### CODE REVIEW

**Comment by sayanarijit** [comment]
It clearly suggests that we should drop python 3.3 support.

```
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pkg_resources/__init__.py", line 92, in <module>
    raise RuntimeError("Python 3.4 or later is required")
RuntimeError: Python 3.4 or later is required
```
Let's do it.

**Comment by sayanarijit** [comment]
Dropped 3.3 in https://github.com/sayanarijit/expandvars/issues/4
Do the following :
```bash
git remote add prod https://github.com/sayanarijit/expandvars
git pull --rebase prod master
git push origin Toilal:setuptools
```
I'll be able to merge it then.

**Comment by sayanarijit** [comment]
Ref: https://github.com/sayanarijit/expandvars/pull/3

**Comment by Toilal** [comment]
Done, build is OK now

**Pull request merged**
